WEEK_TEST_MODULES: dict[int, list[str]] = {
    1: [
        "test_suite_manifest",
        "test_module_imports",
        "test_app",
        "test_api_users",
        "test_api_projects",
        "test_api_dashboard",
        "test_api_platform",
        "test_api_algorithm",
        "test_api_model_library",
        "test_api_chat",
        "test_api_compute",
        "test_api_monitor",
        "test_api_labeling",
        "test_engine_vector_store",
        "test_knowledge",
        "test_agents",
    ],
    2: [
        "test_dag",
        "test_engine_advanced",
        "test_engine_orchestrator",
        "test_run_reliability",
        "test_api_runs",
        "test_api_workflows",
        "test_workflow_versions",
    ],
    3: [
        "test_operator_contract",
        "test_operators_extended",
        "test_operators_mechanism",
        "test_artifact_service",
        "test_api_datasets",
        "test_training",
        "test_training_artifacts",
    ],
    4: [
        "test_weld_demo_service",
        "test_industrial_templates",
        "test_industrial_template_e2e",
    ],
    5: [
        "test_config",
        "test_database_production",
        "test_database_transfer",
        "test_storage",
        "test_artifact_storage_integration",
        "test_operator_artifacts",
        "test_artifact_migration",
        "test_task_dispatcher",
        "test_celery_workflows",
        "test_event_bridge",
        "test_readiness",
        "test_production_stack",
    ],
    6: [
        "test_experiment_config",
        "test_experiment_models",
        "test_experiment_tracking",
        "test_api_experiments",
        "test_iterative_training",
        "test_training_tasks",
        "test_training_recovery",
        "test_automl_tracking",
        "test_tensorboard_gateway",
        "test_experiment_production_stack",
        "test_upload_paths",
    ],
    7: [
        "test_pipeline_scheduler",
        "test_api_schedules",
        "test_project_access",
        "test_api_project_access",
        "test_ci_workflow",
    ],
    8: [
        "test_model_registry_models",
        "test_onnx_conversion",
        "test_model_registry_service",
        "test_inference_runtime",
        "test_inference_deployment",
        "test_api_model_registry",
        "test_inference_production_stack",
    ],
    9: [
        "test_inference_production_models",
        "test_inference_rollout",
        "test_inference_api_keys",
        "test_inference_rate_limit",
        "test_inference_observability",
        "test_model_cards",
        "test_api_inference_production",
    ],
    10: [
        "test_security_hardening",
        "test_platform_audit",
        "test_notification_models",
        "test_notification_outbox",
        "test_notification_channels",
        "test_api_notifications",
        "test_notification_production_stack",
    ],
    11: [
        "test_week11_12_tools",
        "test_week11_contracts",
    ],
    12: [
        "test_week12_security_gates",
        "test_auth_jwt_migration",
        "test_evidence_manifest",
        "test_acceptance_environment",
        "test_notification_receiver_acceptance",
    ],
}


ALL_TEST_MODULES = [
    module
    for week in sorted(WEEK_TEST_MODULES)
    for module in WEEK_TEST_MODULES[week]
]
